### ISSUE TITLE
pip install --user . with Error: No module named 'pip' & No module named 'pybind11'

### ISSUE THREAD

**Issue by lqzhao** [PRBonn/puma#15]
When running "pip install --user . ". I got these error messages, has anyone met this before?

```
(occu) zlq@qh1:/mnt3/zlq/code/puma$ pip install pybind11
Requirement already satisfied: pybind11 in /home/zlq/anaconda3/envs/occu/lib/python3.7/site-packages (2.10.0)

(occu) zlq@qh1:/mnt3/zlq/code/puma$ pip install --user .
Processing /mnt3/zlq/code/puma
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
Getting requirements to build wheel did not run successfully.
exit code: 1
> [27 lines of output]
      Traceback (most recent call last):
        File "/home/zlq/anaconda3/envs/occu/bin/pip", line 5, in <module>
          from pip._internal.cli.main import main
      ModuleNotFoundError: No module named 'pip'
      Traceback (most recent call last):
        File "/home/zlq/anaconda3/envs/occu/bin/pip", line 5, in <module>
          from pip._internal.cli.main import main
      ModuleNotFoundError: No module named 'pip'
      256
      256
      Traceback (most recent call last):
        File "/home/zlq/anaconda3/envs/occu/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/zlq/anaconda3/envs/occu/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/zlq/anaconda3/envs/occu/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-9rghrs16/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-9rghrs16/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-9rghrs16/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 483, in run_setup
          self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-9rghrs16/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      ModuleNotFoundError: No module named 'pybind11'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1
See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by lqzhao** [comment]
This could be avoided by 
```
export CFLAGS='-std=c++11'
python setup.py install
```

**Comment by Zhangjyhhh** [comment]
i have done this"export CFLAGS='-std=c++11'
                                        python setup.py install''
but i get the error message like this 
"  File "/tmp/easy_install-22TRJA/tqdm-4.65.0/temp/easy_install-YG7aHQ/setuptools_scm-7.1.0/setup.py", line 20
    def scm_version() -> str:
                      ^
SyntaxError: invalid     " 
do you have any idea
@lqzhao
