### ISSUE TITLE
no module " pybind11"

### ISSUE THREAD

**Issue by Zhangjyhhh** [PRBonn/puma#20]
thanks for your excellent work.
when i run  this command" docker-compose up --build builder",i get this error message in step 9/16
`Successfully installed easydict-1.10 pykitti-0.3.1 trimesh-3.20.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Processing /puma
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-e_smm85x/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-e_smm85x/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-e_smm85x/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-e_smm85x/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 3, in <module>
      ModuleNotFoundError: No module named 'pybind11'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Service 'builder' failed to build: The command '/bin/sh -c cd /puma     && pip install --no-cache-dir --requirement requirements.txt     && pip install --no-cache-dir --upgrade .     && rm -rf /puma' returned a non-zero code: 1
 `

**Comment by nachovizzo** [comment]
Hello there, I'm not actively supporting this project anymore. I guess that you could try with `sudo apt install pybind11-dev` on the Dockerfile, but I'm not sure about your environment setup.

Maybe someone from the community can help in the future!

**Comment by Zhangjyhhh** [comment]
> 
thanks for your reply

**Comment by boyang9602** [comment]
Hi I solved this problem by adding 
```
[build-system]
requires = ["setuptools", "wheel", "pybind11"]
build-backend = "setuptools.build_meta"
```
in pyproject.toml
